### ISSUE TITLE
When click Dismiss, how to Ajax ?

### ISSUE THREAD

**Issue by guimafx** [MattIPv4/macOSNotifJS#18]
Hello Guys, 
Please, how can i make ajax request, when user click @ DISMISS  btn ?
I should use that make the notification read by the user.
Thanks !
Guilherme

**Comment by MattIPv4** [comment]
Hey @guimafx,

Looks like I've missed this in the documentation, sorry!
You can set `btn1Link` or `btn2Link` to be a function instead of a string URL, which will act as a JavaScript callback when clicked :)

Hope that helps, let me know if you need anything further!

**Comment by MattIPv4** [comment]
Now documented fully on the site (#19)!

**Comment by guimafx** [comment]
**Thanks buddy ! if you have some sample, would be perfect !!!**

{{{ i confess i need to improve some JS skills }}}

**Comment by MattIPv4** [comment]
@MattIPv4 Sure, take a look at https://macosnotif.js.org/docs/macosnotif/0.1.1/#button-configuration and the javascript callback button example.

**Comment by guimafx** [comment]
yeah, worked fine. thanks !
