### ISSUE TITLE
ES6 to minified ES5

### ISSUE THREAD

**Issue by MattIPv4** [MattIPv4/macOSNotifJS#7]
Currently the JS plugin (macOSNotif.js) is unminified and written with ES6.
It also relies on relative resources to run correctly.
Really this needs to be compiled to ES5 and minified.

I think babel & webpack need to be used for this but I frankly have no idea how to do it.

**Comment by MattIPv4** [comment]
The plugin in ES6 form is supported by the latest versions of most main stream browsers however it will not function as intended in IE. Whilst IE isn't used as much anymore, support for this would be nice. https://caniuse.com/#search=es6

Additionally, minification of the script would be great and very few tools appear to support ES6 for minification. I couldn't get any to work at least...

**Comment by Spring3** [comment]
Working on it
